### ISSUE TITLE
Generating More Fortunes

### ISSUE THREAD

**Issue by impulsecorp** [simon-larsson/fortune-cookie-gpt2#1]
Your program works great, but I have a question about the part at the end where it generates the fortunes:
`print(gpt2.generate(max_length=100).replace('<EOS>', '\n\n'))`

Is there any easy way for me to change it so it generates 500 or maybe even 5000 fortunes?

**Comment by simon-larsson** [comment]
Yes. Just increase `max_length=100` to something larger. But the fortunes tend to become a bit less interesting and repetitive if the sequence grows long.

**Comment by impulsecorp** [comment]
That was the first hing I tried already before I contacted you, but it does not seem to make any difference in the output whether 
max_length=100  , 10000 , or 100000. It always gives around the same number of fortunes.

**Comment by simon-larsson** [comment]
Yupp, it's a bug on my end. Will fix that. Thanks for noticing. :)

**Comment by simon-larsson** [comment]
I fixed the bug and added the `min_length` parameter from the huggingface API. Now you can control the sequence length by doing:

`print(gpt2.generate(max_length=1000, min_length=500).replace('<EOS>', '\n\n'))`

But you cannot go arbitrarily large with GPT-2 as you can read [here](https://github.com/huggingface/transformers/issues/4542)

**Comment by impulsecorp** [comment]
Thanks.
